name: weather_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1
  permission_handler: ^11.3.1
  curved_navigation_bar: ^1.0.6
  path_provider: ^2.1.4
  hive: ^2.2.3
  http: ^1.2.2
  flutter_map: ^7.0.2
  geolocator: ^13.0.1
  geocoding: ^3.0.0
dev_dependencies:
  flutter_lints: ^4.0.0
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/logo.jpeg"
flutter:
  uses-material-design: true
  assets:
    - assets/